//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABDOMEN_OBSERVATION
    {
        public int ObsAbdomenID { get; set; }
        public int ForensicCaseID { get; set; }
        public string PeritonealCavity { get; set; }
        public string StomachContents { get; set; }
        public string IntestinesMesentery { get; set; }
        public string LiverGallbladderBilliaryPassages { get; set; }
        public decimal LiverMassKg { get; set; }
        public string Pancreas { get; set; }
        public string Spleen { get; set; }
        public Nullable<decimal> SplenicMassKg { get; set; }
        public string Adrenals { get; set; }
        public string KidneysUreters { get; set; }
        public Nullable<decimal> LeftKidneyMassKg { get; set; }
        public Nullable<decimal> RightKidneyMassKg { get; set; }
        public string UrinaryBladderUrethra { get; set; }
        public string PelvicWalls { get; set; }
        public string GenitalOrgans { get; set; }
    
        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }
    }
}
