//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using DocuPath.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    

    public partial class ACCESS_AREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCESS_AREA()
        {
            this.LEVEL_AREA = new HashSet<LEVEL_AREA>();
        }

        [DisplayName("ID")]
        public int AccessAreaID { get; set; }
        [DisplayName("Function Group")]
        public int FunctionGroupID { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Description")]
        public string AccessAreaDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEVEL_AREA> LEVEL_AREA { get; set; }
        public virtual FUNCTION_GROUP FUNCTION_GROUP { get; set; }
    }
}
