//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVE_LOGIN
    {
        public string DeviceIPAddress { get; set; }
        public int UserID { get; set; }
        public System.DateTime LoginTimestamp { get; set; }
        public System.DateTime LastActionTimestamp { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
