//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDITIONAL_EVIDENCE
    {
        public int AdditionalEvidenceID { get; set; }
        public int ForensicCaseID { get; set; }
        public string EvidenceDescription { get; set; }
        public string EvidenceSerialNumber { get; set; }
        public string ContactPersonNameSurname { get; set; }
        public string ContactPersonContactNum { get; set; }
        public string AdditionalEvidenceLocation { get; set; }
    
        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }
    }
}
