//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_LOG
    {
        public int AuditLogTxID { get; set; }
        public int AuditLogTxTypeID { get; set; }
        public int UserID { get; set; }
        public System.DateTime TxDateStamp { get; set; }
        public System.DateTime TxTimeStamp { get; set; }
        public string TxCriticalDataString { get; set; }
        public string TxOldRecord { get; set; }
        public string TxNewRecord { get; set; }
    
        public virtual AUDIT_TX_TYPE AUDIT_TX_TYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
