//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using DocuPath.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class AUDIT_LOG
    {
        [DisplayName("ID")]
        public int AuditLogTxID { get; set; }
        [DisplayName("Transaction Type")]
        public int AuditLogTxTypeID { get; set; }
        [DisplayName("Origin")]
        public int UserID { get; set; }
        [DisplayName("Datestamp")]
        public System.DateTime TxDateStamp { get; set; }
        [DisplayName("Timestamp")]
        public System.DateTime TxTimeStamp { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Description")]
        public string TxCriticalDataString { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Old Record")]
        public string TxOldRecord { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("New Record")]
        public string TxNewRecord { get; set; }
    
        public virtual AUDIT_TX_TYPE AUDIT_TX_TYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
