//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASE_STATISTICS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CASE_STATISTICS()
        {
            this.STATS_EXTERNAL_CAUSE = new HashSet<STATS_EXTERNAL_CAUSE>();
            this.STATS_INJURY_SCENE = new HashSet<STATS_INJURY_SCENE>();
            this.STATS_POLICE_STATION = new HashSet<STATS_POLICE_STATION>();
            this.STATS_PROVINCE_EVENT = new HashSet<STATS_PROVINCE_EVENT>();
            this.STATS_SAMPLES_INVESTIGATION = new HashSet<STATS_SAMPLES_INVESTIGATION>();
            this.STATS_SPECIAL_CATEGORY = new HashSet<STATS_SPECIAL_CATEGORY>();
            this.STATS_TREATMENTS = new HashSet<STATS_TREATMENTS>();
        }
    
        public int CaseStatsID { get; set; }
        public int ForensicCaseID { get; set; }
        public int ApparentMannerID { get; set; }
        public int AutopsyTypeID { get; set; }
        public Nullable<int> HospitalClinicID { get; set; }
        public int IndividualGenderID { get; set; }
        public int IndividualRaceID { get; set; }
        public Nullable<int> PrimaryCauseID { get; set; }
        public string BodyCollectorSurname { get; set; }
        public string EvisceratorSurname { get; set; }
        public string OrganDissectorSurname { get; set; }
        public Nullable<System.DateTime> EstimatedInjuryDate { get; set; }
        public Nullable<System.DateTime> DiscoveryDate { get; set; }
        public Nullable<System.DateTime> EstimatedDeathDate { get; set; }
        public string IndividualEstimatedAge { get; set; }
        public string MedicalHistory { get; set; }
        public string TreatmentDuration { get; set; }
        public string OtherPrimaryCauseDescription { get; set; }
        public string OtherApparentMannerDescription { get; set; }
        public string AutopsyTypeOtherDescription { get; set; }
        public string HospitalClinicOtherDescription { get; set; }
        public string IndividualGenderOtherDescription { get; set; }
        public string IndividualRaceOtherDescription { get; set; }
    
        public virtual APPARENT_MANNER_DEATH APPARENT_MANNER_DEATH { get; set; }
        public virtual AUTOPSY_TYPE AUTOPSY_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATS_EXTERNAL_CAUSE> STATS_EXTERNAL_CAUSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATS_INJURY_SCENE> STATS_INJURY_SCENE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATS_POLICE_STATION> STATS_POLICE_STATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATS_PROVINCE_EVENT> STATS_PROVINCE_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATS_SAMPLES_INVESTIGATION> STATS_SAMPLES_INVESTIGATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATS_SPECIAL_CATEGORY> STATS_SPECIAL_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATS_TREATMENTS> STATS_TREATMENTS { get; set; }
        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }
        public virtual HOSPITAL_CLINIC HOSPITAL_CLINIC { get; set; }
        public virtual INDIVIDUAL_GENDER INDIVIDUAL_GENDER { get; set; }
        public virtual INDIVIDUAL_RACE INDIVIDUAL_RACE { get; set; }
        public virtual PRIMARY_CAUSE_DEATH PRIMARY_CAUSE_DEATH { get; set; }
    }
}
