//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using DocuPath.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CHEST_OBSERVATION
    {
        [DisplayName("Chest Observation ID")]
        public int ObsChestID { get; set; }
        [DisplayName("Forensic Case ID")]
        public int ForensicCaseID { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Thoracic Cage & Diaphragm")]
        public string ThoracicCageDiaphragm { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Mediastinum & Oesophagus")]
        public string MediastinumOesophagus { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Trachea & Bronchi")]
        public string TracheaBronchi { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Pleura & Lungs")]
        public string PleuraLungs { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Left Lung Mass (kg)")]
        public decimal LeftLungMassKg { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Right Lung Mass (kg)")]
        public decimal RightLungMassKg { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Heart & Pericardium")]
        public string HeartPericardium { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Heart Mass (kg)")]
        public decimal HeartMassKg { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Large Blood Vessels")]
        public string LargeBloodVessels { get; set; }
    
        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }

        public CHEST_OBSERVATION()
        {
        }

        public CHEST_OBSERVATION(int key, int fcKey)
        {
            this.ObsChestID = key;

            this.ForensicCaseID = fcKey;

            setFlags();
        }
        public void setFlags()
        {

            //public string ThoracicCageDiaphragm { get; set; }
            if (ThoracicCageDiaphragm == null)
            {
                ThoracicCageDiaphragm = FLAG.Text;
            }
            //public string MediastinumOesophagus { get; set; }
            if (MediastinumOesophagus == null)
            {
                MediastinumOesophagus = FLAG.Text;
            }
            //public string TracheaBronchi { get; set; }
            if (TracheaBronchi == null)
            {
                TracheaBronchi = FLAG.Text;
            }
            //public string PleuraLungs { get; set; }
            if (PleuraLungs == null)
            {
                PleuraLungs = FLAG.Text;
            }
            //public decimal LeftLungMassKg { get; set; }
            if (LeftLungMassKg == default(decimal))
            {
                LeftLungMassKg = FLAG.Decimal_Three;
            }
            //public decimal RightLungMassKg { get; set; }
            if (RightLungMassKg == default(decimal))
            {
                RightLungMassKg = FLAG.Decimal_Three;
            }
            //public string HeartPericardium { get; set; }
            if (HeartPericardium == null)
            {
                HeartPericardium = FLAG.Text;
            }
            //public decimal HeartMassKg { get; set; }
            if (HeartMassKg == default(decimal))
            {
                HeartMassKg = FLAG.Decimal_Three;
            }
            //public string LargeBloodVessels { get; set; }
            if (LargeBloodVessels == null)
            {
                LargeBloodVessels = FLAG.Text;
            }

        }
    }
}
