//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class CONTENT_TAG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTENT_TAG()
        {
            this.CASE_COD_ESTIMATION = new HashSet<CASE_COD_ESTIMATION>();
            this.MEDIA_TAG = new HashSet<MEDIA_TAG>();
            this.MEDIA_TAG1 = new HashSet<MEDIA_TAG>();
        }

        [DisplayName("ID")]
        public int ContentTagID { get; set; }
        [DisplayName("Category")]
        public int TagCategoryID { get; set; }
        [DisplayName("Subcategory")]
        public int TagSubCategoryID { get; set; }
        [DisplayName("Condition")]
        public int TagConditionID { get; set; }
        [DisplayName("Tag Code")]
        public string ContentTagCode { get; set; }
        [DisplayName("Tag Text")]
        public string ContentTagText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_COD_ESTIMATION> CASE_COD_ESTIMATION { get; set; }
        public virtual TAG_CONDITION TAG_CONDITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDIA_TAG> MEDIA_TAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDIA_TAG> MEDIA_TAG1 { get; set; }
        public virtual TAG_CATEGORY TAG_CATEGORY { get; set; }
        public virtual TAG_CONDITION TAG_CONDITION1 { get; set; }
        public virtual TAG_SUBCATEGORY TAG_SUBCATEGORY { get; set; }
        public virtual TAG_CATEGORY TAG_CATEGORY1 { get; set; }
    }
}
