//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using DocuPath.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EXTERNAL_REVIEW_CASE
    {
        [DisplayName("ID")]
        public int ExternalReviewCaseID { get; set; }
        [DisplayName("Status")]
        public int StatusID { get; set; }
        [DisplayName("Assigned To")]
        public int UserID { get; set; }
        [DefaultValue(FLAG.Alphanumeric)]
        [DisplayName("DR Number")]
        public string ExternalDRNumber { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Brief Description")]
        public string ERCBriefDescription { get; set; }
        //todo date
        [DisplayName("Date Added")]
        public System.DateTime DateAdded { get; set; }
        //todo time 
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Date Closed")]
        public Nullable<System.DateTime> DateClosed { get; set; }
        [DefaultValue(FLAG.Alphanumeric)]
        [DisplayName("Cover Letter")]
        public string CoverLetterLocation { get; set; }
        [DefaultValue(FLAG.Alphanumeric)]
        [DisplayName("External Review Case Report")]
        public string ExtCaseReportLocation { get; set; }
    
        public virtual STATUS STATUS { get; set; }
        public virtual USER USER { get; set; }
    }
}
