//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using DocuPath.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EXTERNAL_REPORT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXTERNAL_REPORT()
        {
            this.SPECIMEN = new HashSet<SPECIMEN>();
        }

        [DisplayName("ID")]
        public int ExternalReportID { get; set; }
        [DisplayName("Date Received")]
        public System.DateTime DateReceived { get; set; }
        [DisplayName("Date Captured")]
        public System.DateTime DateCaptured { get; set; }
        [DefaultValue(FLAG.Alphanumeric)]
        [DisplayName("External Report Location")]
        public string ExternalReportLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPECIMEN> SPECIMEN { get; set; }
    }
}
