//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORENSIC_CASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORENSIC_CASE()
        {
            this.ABDOMEN_OBSERVATION = new HashSet<ABDOMEN_OBSERVATION>();
            this.ADDITIONAL_EVIDENCE = new HashSet<ADDITIONAL_EVIDENCE>();
            this.CASE_COD_ESTIMATION = new HashSet<CASE_COD_ESTIMATION>();
            this.CASE_STATISTICS = new HashSet<CASE_STATISTICS>();
            this.CHEST_OBSERVATION = new HashSet<CHEST_OBSERVATION>();
            this.GENERAL_OBSERVATION = new HashSet<GENERAL_OBSERVATION>();
            this.HEAD_NECK_OBSERVATION = new HashSet<HEAD_NECK_OBSERVATION>();
            this.MEDIA = new HashSet<MEDIA>();
            this.SERVICE_REQUEST = new HashSet<SERVICE_REQUEST>();
            this.SPINE_OBSERVATION = new HashSet<SPINE_OBSERVATION>();
        }
    
        public int ForensicCaseID { get; set; }
        public int StatusID { get; set; }
        public int SessionID { get; set; }
        public int AutopsyAreaID { get; set; }
        public int UserID { get; set; }
        public string ForensicDRNumber { get; set; }
        public string FCBriefDescription { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string DHANoticeDeathID { get; set; }
        public string ActingOfficerNameSurname { get; set; }
        public string ActingOfficerContactNum { get; set; }
        public string CauseOfDeathConclusion { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABDOMEN_OBSERVATION> ABDOMEN_OBSERVATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADDITIONAL_EVIDENCE> ADDITIONAL_EVIDENCE { get; set; }
        public virtual AUTOPSY_AREA AUTOPSY_AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_COD_ESTIMATION> CASE_COD_ESTIMATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CASE_STATISTICS> CASE_STATISTICS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHEST_OBSERVATION> CHEST_OBSERVATION { get; set; }
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENERAL_OBSERVATION> GENERAL_OBSERVATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HEAD_NECK_OBSERVATION> HEAD_NECK_OBSERVATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDIA> MEDIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE_REQUEST> SERVICE_REQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPINE_OBSERVATION> SPINE_OBSERVATION { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual USER USER { get; set; }
    }
}
