//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using DocuPath.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class GENERAL_OBSERVATION
    {
        [DisplayName("General Observation ID")]
        public int ObsGeneralID { get; set; }
        [DisplayName("Forensic Case ID")]
        public int ForensicCaseID { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("General Description")]
        public string GeneralDescription { get; set; }
        //[DefaultValue(FLAG.Decimal_Three)]
        [DisplayName("Height (m)")]
        public decimal HeightMeters { get; set; }
        //[DefaultValue(FLAG.Decimal_Three)]
        [DisplayName("Mass (kg)")]
        public decimal MassKg { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Physique")]
        public string Physique { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Nutrition")]
        public string Nutrition { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Special Identifying Features")]
        public string SpecialIdentifyingFeatures { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Secondary Postmortem Changes")]
        public string SecondaryPostMortemChanges { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("External Appearance & Limb Condition")]
        public string ExtAppearanceLimbCondition { get; set; }

        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }

        public GENERAL_OBSERVATION()
        {
        }

        public GENERAL_OBSERVATION(int key, int fcKey)
        {
            this.ObsGeneralID = key;

            this.ForensicCaseID = fcKey;

            setFlags();

        }
        public void setFlags()
        {
            //public string GeneralDescription { get; set; }
            if (GeneralDescription == null)
            {
                GeneralDescription = FLAG.Text;
            }

            //public decimal HeightMeters { get; set; }
            if (HeightMeters == default(decimal))
            {
                HeightMeters = FLAG.Decimal_Three;
            }

            //public decimal MassKg { get; set; }
            if (MassKg == default(decimal))
            {
                MassKg = FLAG.Decimal_Three;
            }

            //public string Physique { get; set; }
            if (Physique == null)
            {
                Physique = FLAG.Text;
            }

            //public string Nutrition { get; set; }
            if (Nutrition == null)
            {
                Nutrition = FLAG.Text;
            }

            //public string SpecialIdentifyingFeatures { get; set; }
            if (SpecialIdentifyingFeatures == null)
            {
                SpecialIdentifyingFeatures = FLAG.Text;
            }

            //public string SecondaryPostMortemChanges { get; set; }
            if (SecondaryPostMortemChanges == null)
            {
                SecondaryPostMortemChanges = FLAG.Text;
            }

            //public string ExtAppearanceLimbCondition { get; set; }
            if (ExtAppearanceLimbCondition == null)
            {
                ExtAppearanceLimbCondition = FLAG.Text;
            }
        }
    }
}
