//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using DocuPath.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HEAD_NECK_OBSERVATION
    {
        [DisplayName("Head & Neck Observation ID")]
        public int ObsHeadNeckID { get; set; }
        [DisplayName("Forensic Case ID")]
        public int ForensicCaseID { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Scalp & Skull")]
        public string ScalpSkull { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Intracranial Contents")]
        public string IntracranialContents { get; set; }
        // [DefaultValue(FLAG.Decimal_Three)]
        [DisplayName("Brain Mass (kg)")]
        public decimal BrainMassKg { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Orbital, Nasal & Aural Cavities")]
        public string OrbitalNasalAuralCavities { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Mouth, Tongue & Pharynx")]
        public string MouthTonguePharynx { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Neck Structures")]
        public string NeckStructures { get; set; }

        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }

        public HEAD_NECK_OBSERVATION()
        {
        }
        public HEAD_NECK_OBSERVATION(int key, int fcKey)
        {
            this.ObsHeadNeckID = key;

            this.ForensicCaseID = fcKey;

            setFlags();
        }
        public void setFlags()
        {

            //public string ScalpSkull { get; set; }
            if (ScalpSkull == null)
            {
                ScalpSkull = FLAG.Text;
            }
            //public string IntracranialContents { get; set; }
            if (IntracranialContents == null)
            {
                IntracranialContents = FLAG.Text;
            }
            //public decimal BrainMassKg { get; set; }
            if (BrainMassKg == default(decimal))
            {
                BrainMassKg = FLAG.Decimal_Three;
            }
            //public string OrbitalNasalAuralCavities { get; set; }
            if (OrbitalNasalAuralCavities == null)
            {
                OrbitalNasalAuralCavities = FLAG.Text;
            }
            //public string MouthTonguePharynx { get; set; }
            if (MouthTonguePharynx == null)
            {
                MouthTonguePharynx = FLAG.Text;
            }
            //public string NeckStructures { get; set; }
            if (NeckStructures == null)
            {
                NeckStructures = FLAG.Text;
            }

        }
    }
}
