//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using DocuPath.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LEGACY_CASE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LEGACY_CASE()
        {
            this.LEGACY_DOCUMENT = new HashSet<LEGACY_DOCUMENT>();
        }

        [DisplayName("ID")]
        public int LegacyCaseID { get; set; }
        [DisplayName("Status")]
        public int StatusID { get; set; }
        [DisplayName("Added By")]
        public int UserID { get; set; }
        [DefaultValue(FLAG.Alphanumeric)]
        [DisplayName("DR Number")]
        public string LegacyDRNumber { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Brief Description")]
        public string LCBriefDescription { get; set; }
        //todo [DefaultValue(FLAG.Text)]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Date Added")]
        public System.DateTime DateAdded { get; set; }
        //todo [DefaultValue(FLAG.Text)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Date Closed")]
        public Nullable<System.DateTime> DateClosed { get; set; }
    
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEGACY_DOCUMENT> LEGACY_DOCUMENT { get; set; }
        public virtual USER USER { get; set; }
    }
}
