//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using DocuPath.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MEDIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDIA()
        {
            this.MEDIA_TAG = new HashSet<MEDIA_TAG>();
        }

        [DisplayName("ID")]
        public int MediaID { get; set; }
        [DisplayName("Status")]
        public int StatusID { get; set; }
        [DisplayName("Related Case")]
        public Nullable<int> ForensicCaseID { get; set; }
        [DisplayName("Purpose")]
        public int MediaPurposeID { get; set; }
        [DisplayName("Added By")]
        public int UserID { get; set; }
        //todo [DefaultValue(FLAG.Text)]
        [DisplayName("Date Added")]
        public System.DateTime DateAdded { get; set; }
        [DefaultValue(FLAG.Text)]
        [Required]
        [DisplayName("Caption")]
        public string MediaCaption { get; set; }
        [DefaultValue(FLAG.Text)]
        [Required]
        [DataType(DataType.MultilineText)]
        [StringLength(235)]
        [DisplayName("Description")]
        public string MediaDescription { get; set; }
        [DisplayName("Accessibility")]
        public bool IsPubliclyAccessible { get; set; }
        [DefaultValue(FLAG.Alphanumeric)]
        [DisplayName("Item Location")]
        public string MediaLocation { get; set; }
    
        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }
        public virtual MEDIA_PURPOSE MEDIA_PURPOSE { get; set; }
        public virtual USER USER { get; set; }
        public virtual STATUS STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDIA_TAG> MEDIA_TAG { get; set; }
    }
}
