//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NOTIFICATION
    {
        [DisplayName("ID")]
        public int NotificationID { get; set; }
        [DisplayName("Target User")]
        public int UserID { get; set; }
        [DisplayName("Type")]
        public int NotificationTypeID { get; set; }
        [DisplayName("Creation Stamp")]
        public System.DateTime DateID { get; set; }
        [DisplayName("Title")]
        public string NotificationTitle { get; set; }
        [DisplayName("Summary")]
        public string NotificationSummary { get; set; }
        [DisplayName("Details")]
        public string NotificationDetails { get; set; }
        [DisplayName("Handling Stamp")]
        public Nullable<System.DateTime> HandledDateTimeStamp { get; set; }
    
        public virtual NOTIFICATION_TYPE NOTIFICATION_TYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
