//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIAL_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPECIAL_CATEGORY()
        {
            this.STATS_SPECIAL_CATEGORY = new HashSet<STATS_SPECIAL_CATEGORY>();
        }
    
        public int SpecialCategoryID { get; set; }
        public string SpecialCategoryDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATS_SPECIAL_CATEGORY> STATS_SPECIAL_CATEGORY { get; set; }
    }
}
