//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIMEN
    {
        public int SpecimenID { get; set; }
        public int ServiceRequestID { get; set; }
        public Nullable<int> ExternalReportID { get; set; }
        public int ServiceProviderID { get; set; }
        public string InvestigationRequired { get; set; }
        public string DisposalMechanism { get; set; }
        public string SpecimenNature { get; set; }
        public string SpecimenSerialNumber { get; set; }
    
        public virtual EXTERNAL_REPORT EXTERNAL_REPORT { get; set; }
        public virtual SERVICE_REQUEST SERVICE_REQUEST { get; set; }
    }
}
