//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPINE_OBSERVATION
    {
        public int ObsSpineID { get; set; }
        public int ForensicCaseID { get; set; }
        public string SpinalColumn { get; set; }
        public string SpinalCord { get; set; }
    
        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }
    }
}
