//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using DocuPath.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SYSTEM_FLAG
    {
        [DisplayName("ID")]
        public string SysFlagID { get; set; }
        [DefaultValue(FLAG.Text)]
        [DisplayName("Flag Description")]
        public string SysFlagDescription { get; set; }
    }
}
