//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKEN_LOG
    {
        public int TokenID { get; set; }
        public int AccessLevelID { get; set; }
        public int UserID { get; set; }
        public string TokenValue { get; set; }
        public System.DateTime IssueTimestamp { get; set; }
        public Nullable<System.DateTime> RedemptionTimestamp { get; set; }
        public string DestinationEmail { get; set; }
    
        public virtual USER USER { get; set; }
        public virtual ACCESS_LEVEL ACCESS_LEVEL { get; set; }
    }
}
