//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.ACTIVE_LOGIN = new HashSet<ACTIVE_LOGIN>();
            this.AUDIT_LOG = new HashSet<AUDIT_LOG>();
            this.EXTERNAL_REVIEW_CASE = new HashSet<EXTERNAL_REVIEW_CASE>();
            this.FORENSIC_CASE = new HashSet<FORENSIC_CASE>();
            this.FPS_AUTOPSY_SCHEDULE = new HashSet<FPS_AUTOPSY_SCHEDULE>();
            this.LEGACY_CASE = new HashSet<LEGACY_CASE>();
            this.MEDIA = new HashSet<MEDIA>();
            this.NOTIFICATION = new HashSet<NOTIFICATION>();
            this.SESSION_USER = new HashSet<SESSION_USER>();
            this.TOKEN_LOG = new HashSet<TOKEN_LOG>();
            this.USER_CLAIM = new HashSet<USER_CLAIM>();
        }

        [DisplayName("ID")]
        public int UserID { get; set; }
        [DisplayName("Title")]
        public int TitleID { get; set; }
        [DisplayName("Login ID")]
        public Nullable<int> UserLoginID { get; set; }
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [DisplayName("Middle Name")]
        public string MiddleName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [DisplayName("Initials")]
        public string DisplayInitials { get; set; }
        [DisplayName("Qualification Description")]
        public string QualificationDescription { get; set; }
        [DisplayName("HPCSA Registration Number")]
        public string HPCSARegNumber { get; set; }
        [DisplayName("National ID")]
        public string NationalID { get; set; }
        [DisplayName("Academic ID")]
        public string AcademicID { get; set; }
        [DisplayName("Cellphone Number")]
        public string CellNum { get; set; }
        [DisplayName("Telephone Number")]
        public string TelNum { get; set; }
        [DisplayName("Work Number")]
        public string WorkNum { get; set; }
        [DisplayName("Personal Email")]
        public string PersonalEmail { get; set; }
        [DisplayName("Academic Email")]
        public string AcademicEmail { get; set; }
        [DisplayName("Physical Address")]
        public string PhysicalAddress { get; set; }
        [DisplayName("Postal Address")]
        public string PostalAddress { get; set; }
        [DisplayName("Status")]
        public bool IsDeactivated { get; set; }
        [DisplayName("Dark UI Preferred")]
        public Nullable<bool> DarkUIPref { get; set; }
        [DisplayName("Username")]
        public string UserName { get; set; }
        [DisplayName("Confirmation Status")]
        public bool IsConfirmed { get; set; }
        [DisplayName("Security Stamp")]
        public string SecurityStamp { get; set; }
        [DisplayName("Lockout Enabled")]
        public Nullable<bool> LockoutEnabled { get; set; }
        [DisplayName("Lockout End Date")]
        public Nullable<bool> LockoutEndDate { get; set; }
        [DisplayName("Access Failure Count")]
        public int AccessFailedCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVE_LOGIN> ACTIVE_LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDIT_LOG> AUDIT_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTERNAL_REVIEW_CASE> EXTERNAL_REVIEW_CASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORENSIC_CASE> FORENSIC_CASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FPS_AUTOPSY_SCHEDULE> FPS_AUTOPSY_SCHEDULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEGACY_CASE> LEGACY_CASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDIA> MEDIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SESSION_USER> SESSION_USER { get; set; }
        public virtual TITLE TITLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOKEN_LOG> TOKEN_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_CLAIM> USER_CLAIM { get; set; }
        public virtual USER_LOGIN USER_LOGIN { get; set; }
    }
}
