//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPS_DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FPS_DOCTOR()
        {
            this.FPS_SCHEDULE_DOCTOR = new HashSet<FPS_SCHEDULE_DOCTOR>();
        }
    
        public int FPSDoctorID { get; set; }
        public string FPSDoctorName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FPS_SCHEDULE_DOCTOR> FPS_SCHEDULE_DOCTOR { get; set; }
    }
}
