//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERAL_OBSERVATION
    {
        public int ObsGeneralID { get; set; }
        public int ForensicCaseID { get; set; }
        public string GeneralDescription { get; set; }
        public decimal HeightMeters { get; set; }
        public decimal MassKg { get; set; }
        public string Physique { get; set; }
        public string Nutrition { get; set; }
        public string SpecialIdentifyingFeatures { get; set; }
        public string SecondaryPostMortemChanges { get; set; }
        public string ExtAppearanceLimbCondition { get; set; }
    
        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }
    }
}
