//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int NotificationID { get; set; }
        public int UserID { get; set; }
        public int NotificationTypeID { get; set; }
        public System.DateTime DateID { get; set; }
        public string NotificationTitle { get; set; }
        public string NotificationSummary { get; set; }
        public string NotificationDetails { get; set; }
        public Nullable<System.DateTime> HandledDateTimeStamp { get; set; }
    
        public virtual NOTIFICATION_TYPE NOTIFICATION_TYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
