//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEST_OBSERVATION
    {
        public int ObsChestID { get; set; }
        public int ForensicCaseID { get; set; }
        public string ThoracicCageDiaphragm { get; set; }
        public string MediastinumOesophagus { get; set; }
        public string TracheaBronchi { get; set; }
        public string PleuraLungs { get; set; }
        public decimal LeftLungMassKg { get; set; }
        public decimal RightLungMassKg { get; set; }
        public string HeartPericardium { get; set; }
        public decimal HeartMassKg { get; set; }
        public string LargeBloodVessels { get; set; }
    
        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }
    }
}
