//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTERNAL_REVIEW_CASE
    {
        public int ExternalReviewCaseID { get; set; }
        public int StatusID { get; set; }
        public int UserID { get; set; }
        public string ExternalDRNumber { get; set; }
        public string BriefDescription { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string CoverLetterLocation { get; set; }
        public string ExtCaseReportLocation { get; set; }
    
        public virtual STATUS STATUS { get; set; }
        public virtual USER USER { get; set; }
    }
}
