//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPS_ASSISTANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FPS_ASSISTANT()
        {
            this.FPS_CASE = new HashSet<FPS_CASE>();
            this.FPS_SCHEDULE_ASSISTANT = new HashSet<FPS_SCHEDULE_ASSISTANT>();
        }
    
        public int FPSAssistantID { get; set; }
        public string FPSAssistantName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FPS_CASE> FPS_CASE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FPS_SCHEDULE_ASSISTANT> FPS_SCHEDULE_ASSISTANT { get; set; }
    }
}
