//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPS_SCHEDULE_DOCTOR
    {
        public System.DateTime FPSScheduleDate { get; set; }
        public int FPSDoctorID { get; set; }
        public int FPSStaffRankID { get; set; }
    
        public virtual FPS_AUTOPSY_SCHEDULE FPS_AUTOPSY_SCHEDULE { get; set; }
        public virtual FPS_DOCTOR FPS_DOCTOR { get; set; }
        public virtual FPS_STAFF_RANK FPS_STAFF_RANK { get; set; }
    }
}
