//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPS_AUTOPSY_SCHEDULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FPS_AUTOPSY_SCHEDULE()
        {
            this.FPS_SCHEDULE_ASSISTANT = new HashSet<FPS_SCHEDULE_ASSISTANT>();
            this.FPS_SCHEDULE_DOCTOR = new HashSet<FPS_SCHEDULE_DOCTOR>();
            this.FPS_CASE = new HashSet<FPS_CASE>();
        }
    
        public System.DateTime FPSScheduleDate { get; set; }
        public int UserID { get; set; }
        public string ReceptionStaff { get; set; }
        public string DryHandsStaff { get; set; }
        public string LodoxStaff { get; set; }
        public string PrimaryBodyReleaseStaff { get; set; }
        public string SecondaryBodyReleaseStaff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FPS_SCHEDULE_ASSISTANT> FPS_SCHEDULE_ASSISTANT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FPS_SCHEDULE_DOCTOR> FPS_SCHEDULE_DOCTOR { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FPS_CASE> FPS_CASE { get; set; }
    }
}
