//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_REQUEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICE_REQUEST()
        {
            this.SPECIMEN = new HashSet<SPECIMan>();
        }
    
        public int ServiceRequestID { get; set; }
        public int ServiceProviderID { get; set; }
        public int RequestTypeID { get; set; }
        public Nullable<int> ForensicCaseID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string RequestNote { get; set; }
        public decimal IsCancelled { get; set; }
    
        public virtual FORENSIC_CASE FORENSIC_CASE { get; set; }
        public virtual REQUEST_TYPE REQUEST_TYPE { get; set; }
        public virtual SERVICE_PROVIDER SERVICE_PROVIDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPECIMan> SPECIMEN { get; set; }
    }
}
