//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION_USER
    {
        public int SessionID { get; set; }
        public int UserID { get; set; }
        public int AllocationStatusID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateStatusChanged { get; set; }
    
        public virtual ALLOCATION_STATUS ALLOCATION_STATUS { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual USER USER { get; set; }
    }
}
