//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocuPath.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATS_PROVINCE_EVENT
    {
        public int CaseStatsID { get; set; }
        public int ForensicCaseID { get; set; }
        public int EventID { get; set; }
        public int ProvinceID { get; set; }
        public string ProvinceOtherDescription { get; set; }
    
        public virtual CASE_STATISTICS CASE_STATISTICS { get; set; }
        public virtual EVENT EVENT { get; set; }
        public virtual PROVINCE PROVINCE { get; set; }
    }
}
